repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: ../charts/nginx-ingress

  - name: cert-manager
    namespace: cert-manager
    chart: ../charts/cert-manager
    values:
      - dnsProvider:
          secret:
            value: {{ requiredEnv "DIGITALOCEAN_API_TOKEN" }}

