apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: {{ include "terraform.fullname" . }}
  labels: {{ include "terraform.labels" . | indent 4 }}
spec:
  module:
    source: {{ .Values.terraform.moduleRepository }}
  organization: {{ .Values.terraform.syncWorkspace.organization }}
  secretsMountPath: "/tmp/secrets"
  variables:
    - environmentVariable: false
      key: loadbalancer_name
      sensitive: false
      value: nginx-ingress-controller
    - environmentVariable: false
      key: loadbalancer_namespace
      sensitive: false
      value: kube-system
    - environmentVariable: false
      key: ingress_dns
      value: {{ .Values.ingress.host }}
