brew cask "kontena/lens/lens"

brew "container-structure-test"
brew "helm"
brew "helmfile"
brew "hyperkit"
brew "kubernetes-cli"
brew "minikube"
brew "mkcert"
brew "skaffold"
brew "terraform"
brew "tflint"
brew "terraform-docs"
