apiVersion: skaffold/v2alpha4
kind: Config
build:
  local:
    push: false
    concurrency: 0
    useBuildkit: true
  tagPolicy:
    sha256: {}
  artifacts:
  - image: spotishake/web
    context: web
  - image: spotishake/api
    context: api
    docker:
      buildArgs:
        env: "{{ .NODE_ENV }}"
        apolloEngineKey: "{{ .APOLLO_ENGINE_KEY }}"
deploy:
  helm:
    releases:
    - name: spotishake-web
      chartPath: web
      values:
        image: spotishake/web
    - name: spotishake-api
      chartPath: api
      values:
        image: spotishake/api
