# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
certManager:
  namespace: cert-manager
  clusterIssuerName: letsencrypt

docker:
  name: github
  credentials:
    registry: docker.pkg.github.com
    username: ""
    password: ""

dnsProvider:
  name: digitalocean
  secret:
    key: api-token
    value: ""

acme:
  url: https://acme-v02.api.letsencrypt.org/directory
  email: admin@spotishake.me
