apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
  - name: prometheus-operator
    version: 8.15.5
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: metrics-server
    version: 2.11.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: prometheus-adapter
    version: 2.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
