prometheus-operator:
  kubeTargetVersionOverride: v1.17.5
  prometheusOperator:
    createCustomResource: false
  prometheus:
    service:
      port: 9090
  grafana:
    ingress:
      tls:
        - secretName: grafana-tls
          hosts: [grafana.spotishake.me]
      hosts: [grafana.spotishake.me]
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"

metrics-server:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP

prometheus-adapter:
  prometheus:
    url: http://prometheus-prometheus-oper-prometheus.kube-system.svc
    port: 9090
