apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName }}
spec:
  acme:
    privateKeySecretRef:
      name: {{ printf "%s-%s" .Values.certManager.clusterIssuerName "acme" }}
    email: {{ .Values.acme.email }}
    server: {{ .Values.acme.url }}
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: {{ .Values.dnsProvider.name }}
              key: {{ .Values.dnsProvider.secret.key }}
