apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dnsProvider.name }}
  namespace: {{ .Values.certManager.namespace }}
data:
  {{ .Values.dnsProvider.secret.key }}: {{ .Values.dnsProvider.secret.value | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.docker.name }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.docker.credentials.registry (printf "%s:%s" .Values.docker.credentials.username .Values.docker.credentials.password | b64enc) | b64enc }}

