name: Docker images
on: [push]
jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.pkg.github.com/${{ github.repository }}
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN  }}
      NODE_ENV: production
      REACT_APP_PUBLIC_URL: https://api.spotishake.me/graphql
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          repository: api
          path: api
          push: true
          tags: latest
      - uses: docker/build-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          repository: web
          path: web
          push: true
          tags: latest
          build_args: apiUrl=$REACT_APP_PUBLIC_URL env=$NODE_ENV
