name: Infrastructure provision
on: [push]
defaults:
  run:
    working-directory: cloud
jobs:
  terraform:
    name: Terraform cloud infrastructure
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.0.1
        with:
          terraform_version: 0.13.0-beta2
      - name: Initialize modules
        run: terraform init
      - name: Validate syntax
        run: terraform validate -no-color
      - name: Plan required changes
        run: terraform plan -var digitalocean_api_token=${{ secrets.DIGITALOCEAN_API_TOKEN }} -input=false -no-color
      - name: Apply plans
        run: terraform apply -var digitalocean_api_token=${{ secrets.DIGITALOCEAN_API_TOKEN }} -input=false -auto-approve
  helm:
    name: Deploy Helm charts
    runs-on: ubuntu-latest
    needs:
      - terraform
    env:
      KUBECONFIG: ${{ github.workspace }}/cloud/.kube/config
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Helm
        uses: mamezou-tech/setup-helmfile@v0.3.0
        with:
          helmfile-version: v0.119.0
          helm-version: v3.2.4
          kubectl-version: v1.18.2
      - name: Create Kubernetes CRDs
        run: helm upgrade --install --cleanup-on-fail --atomic crds charts/crds
      - name: Deploy Helm charts
        run: helmfile apply
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
