name: Application deployments
on: [push]
jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloud
    steps:
      - uses: actions/checkout@v2
      - uses: mamezou-tech/setup-helmfile@v0.2.4
        with:
          helmfile-version: "v0.116.0"
          helm-version: "v3.2.1"
          kubectl-version: "v1.18.0"
      - run: |
          mkdir -p ~/.kube
          echo '${{ secrets.kubeconfig }}' >> ~/.kube/config
          helm plugin install https://github.com/databus23/helm-diff --version master
      - run: helmfile apply
        env:
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.grafana_admin_password }}
          DIGITALOCEAN_API_TOKEN: ${{ secrets.digitalocean_api_token }}
