name: Application deployments
on: [push]
jobs:
  deploy:
    name: Helm
    runs-on: ubuntu-latest
    env:
      GRAFANA_ADMIN_PASSWORD: ${{ secrets.grafana_admin_password }}
      DIGITALOCEAN_API_TOKEN: ${{ secrets.digitalocean_api_token }}
    steps:
      - uses: actions/checkout@v2
      - uses: mamezou-tech/setup-helmfile@v0.2.4
        with:
          helmfile-version: "v0.116.0"
      - working-directory: cloud
        run: helmfile diff
      - working-directory: cloud
        run: helmfile apply
