name: Infrastructure provision
on: [push]
env:
  DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
defaults:
  run:
    working-directory: cloud
jobs:
  terraform:
    name: Terraform cloud infrastructure
    env:
      TF_VAR_digitalocean_api_token: $DIGITALOCEAN_API_TOKEN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13-beta1
      - name: Initialize modules
        run: terraform init
      - name: Validate syntax
        run: terraform validate
      - name: Plan required changes
        run: terraform plan -input=false
      - name: Apply plans
        run: terraform apply -input=false -auto-approve
  helm:
    name: Deploy Helm charts
    runs-on: ubuntu-latest
    needs:
      - terraform
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Helm
        uses: mamezou-tech/setup-helmfile@v0.3.0
        with:
          helmfile-version: v0.119.0
          helm-version: v3.2.4
          kubectl-version: v1.18.2
      - name: Create Kubernetes CRDs
        run: helm upgrade --install --cleanup-on-fail --atomic crds charts/crds
      - name: Deploy Helm charts
        run: helmfile apply
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
