name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      NODE_ENV: production
      REACT_APP_PUBLIC_URL: https://api.spotishake.me/graphql
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com/hiberbee/spotishake
          repository: api
          path: api
          push: true
          tags: latest
          build_args: apiUrl=$REACT_APP_PUBLIC_URL env=$NODE_ENV

      - uses: docker/build-push-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com/hiberbee/spotishake
          repository: web
          path: web
          push: true
          tags: latest
          build_args: apiUrl=$REACT_APP_PUBLIC_URL env=$NODE_ENV
