on: [push]
jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloud
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform validate
      - id: plan
        run: terraform plan -var digitalocean_api_token=${{ secrets.digitalocean_api_token }} -out plan.tf
